source("./00-load-packages.R")

codeDefinitions <- list()

# Thomson Reuters Mutual Funds
# Code definitions
codeDefinitions$ioc <- c("1" ="International",
                         "2" = "Aggresive growth",
                         "3" = "Growth",
                         "4" = "Growth & income",
                         "5" = "Municipal bonds",
                         "6" = "Bond and preferred",
                         "7" = "Balanced",
                         "8" = "Metals",
                         "9" = "Unclassified")

codeDefinitions$exchcd <- c("A" = "NYSE",
                            "B" = "AMES",
                            "C" = "PBW & Boston",
                            "D" = "Midwest",
                            "E" = "Pacific",
                            "F" = "NASDAQ Small",
                            "I" = "OTC Mutual Funds",
                            "J" = "Toronto",
                            "K" = "Montreal",
                            "V" = "NASDAQ National",
                            "W" = "Vancouver",
                            "Z" = "Alberta")

codeDefinitions$stkcd <- c("0" = "Common stock",
                           "7" = "Mutual fund",
                           "+" = "Foreign stock")

codeDefinitions$stkcdesc <- c("CMA" = "Common class A",
                              "CMB" = "Common class B",
                              "CMC" = "Common class C",
                              "COM" = "Common stock",
                              "OR" = "Ordinary share",
                              "PR" = "Preferred stock",
                              "RG" = "Right",
                              "RT" = "Receipt",
                              "UNT" = "Unit")

codeDefinitions$indcode <- c("100" = "Unknown",
                             "101" = "Aerospace",
                             "102" = "Agriculture",
                             "103" = "Airlines",
                             "104" = "Automobiles",
                             "105" = "Banks & savings institutions",
                             "106" = "Beverages",
                             "107" = "Chemicals",
                             "108" = "Computer hardware, software & services",
                             "109" = "Construction & engineering",
                             "110" = "Consumer services",
                             "111" = "Electrical & electronics",
                             "112" = "Miscellaneous",
                             "113" = "Energy & fuels",
                             "114" = "Financial services",
                             "115" = "Food & restaurants",
                             "116" = "Healthcare",
                             "117" = "House wares & household items",
                             "118" = "Industrial manufacturing",
                             "119" = "Insurance",
                             "120" = "Investment services",
                             "121" = "Leisure travel & lodging",
                             "122" = "Machincery & equipment",
                             "123" = "Media",
                             "124" = "Metals & mining",
                             "125" = "Packaging",
                             "126" = "Paper & forest products",
                             "127" = "Publishing & printing",
                             "128" = "Real estate",
                             "129" = "Retail & consumer goods",
                             "130" = "Semiconductors",
                             "131" = "Telecommunications",
                             "132" = "Textiles & apparel",
                             "133" = "Tobacco",
                             "134" = "Transportation",
                             "135" = "Utilities: water-electric-gas",
                             "136" = "Waste & environment management")